name: CI
on: [ push, workflow_dispatch ]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.0', '8.1', '8.2' ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, tokenizer
          ini-values: post_max_size=256M, log_errors=1
          coverage: xdebug
          tools: pecl
      - name: Install composer dependencies
        run: composer install --prefer-dist
      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse -c phpstan.neon
      - name: Run Psalm
        run: php vendor/bin/psalm -c psalm.xml
      - name: Run PHPUnit
        run: php vendor/bin/phpunit --coverage-text
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
